server:
  port: 8084

spring:
  application:
    name: hots-seckill-service
  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 9999

  #消息队列
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    password: admin
    username: admin
    #开启手动确认消息
    listener:
      simple:
        acknowledge-mode: manual

  main:
    allow-bean-definition-overriding: true
  #redis 配置
  redis:
    host: localhost
    port: 8000
    password: 123456


mqconfig:

  #订单队列
  order_queue: order.queue

  #交换机
  order_event_exchange: order.event.exchange

  #进入订单队列的key
  order_routing_key: order.routing.key

#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO




